export const demoGraph = {
  nodes: [
    {
      id: "person:arjun",
      type: "personNode",
      position: { x: 650, y: 320 },
      data: {
        entityType: "person",
        recordId: "arjun",
        label: "Arjun Rao",
        role: "Primary suspect",
        riskScore: 92,
        imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
        aliases: ["Red Helmet", "A.R."],
        phoneNumbers: ["+919876543210", "+918888777666"],
        address: "Wilson Garden, Bengaluru",
        relationToCase: "Seen near ATM loot site and linked to recovered bike KA01AB1234.",
        metadata: [
          "3 prior theft investigations",
          "Known associate of Mahesh K",
          "Usually operates between 19:00 and 23:00",
          "Helmet color reported in two FIRs",
        ],
        boardType: "suspect photo",
      },
    },
    {
      id: "person:mahesh",
      type: "personNode",
      position: { x: 210, y: 120 },
      data: {
        entityType: "person",
        recordId: "mahesh",
        label: "Mahesh K",
        role: "Associate",
        riskScore: 77,
        imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=160&q=80",
        aliases: ["MK", "Mechanic"],
        address: "Yeshwanthpur, Bengaluru",
        relationToCase: "Garage contact who serviced stolen motorcycles.",
        metadata: ["Vehicle disposal specialist", "Linked by phone CDR", "Family relation: cousin of Arjun"],
        boardType: "associate photo",
      },
    },
    {
      id: "person:unknown-deceased",
      type: "personNode",
      position: { x: 1090, y: 560 },
      data: {
        entityType: "person",
        recordId: "unknown-deceased",
        label: "Unidentified deceased male",
        role: "Victim / evidence carrier",
        riskScore: 36,
        aliases: ["John Doe 17"],
        relationToCase: "Recovered stolen phone found in pocket during postmortem intake.",
        metadata: ["Phone IMEI matches ATM witness report", "Body recovered near railway siding", "No verified family record"],
        boardType: "victim record",
      },
    },
    {
      id: "incident:atm",
      type: "incidentNode",
      position: { x: 1050, y: 190 },
      data: {
        entityType: "incident",
        recordId: "atm",
        title: "ATM cash loot",
        category: "Robbery",
        incidentNumber: "FIR-ATM-1842",
        timeBucket: "night",
        metadata: ["Cash cassette forced open", "CCTV masked", "Blue motorcycle seen exiting lane"],
        boardType: "case file",
      },
    },
    {
      id: "incident:bike",
      type: "incidentNode",
      position: { x: 220, y: 380 },
      data: {
        entityType: "incident",
        recordId: "bike",
        title: "Bike stolen from market",
        category: "Vehicle Theft",
        incidentNumber: "FIR-VT-1109",
        metadata: ["Registration KA01AB1234", "Stolen 48 hours before ATM loot", "Ignition tampered"],
        boardType: "case file",
      },
    },
    {
      id: "location:kr",
      type: "locationNode",
      position: { x: 500, y: 600 },
      data: {
        entityType: "location",
        recordId: "kr",
        title: "KR Market",
        district: "Bengaluru Urban",
        latitude: 12.9601,
        longitude: 77.5767,
        metadata: ["Bike theft origin", "High evening theft density", "Nearest station: City Market PS"],
        boardType: "map fragment",
      },
    },
    {
      id: "location:atm",
      type: "locationNode",
      position: { x: 1390, y: 120 },
      data: {
        entityType: "location",
        recordId: "atm-loc",
        title: "ATM kiosk, Wilson Garden",
        district: "Bengaluru Urban",
        latitude: 12.9498,
        longitude: 77.5968,
        metadata: ["Camera blind spot", "Two approach roads", "Patrol gap 21:00-22:30"],
        boardType: "map fragment",
      },
    },
    {
      id: "vehicle:bike",
      type: "vehicleNode",
      position: { x: 620, y: 70 },
      data: {
        entityType: "vehicle",
        recordId: "bike",
        registrationNo: "KA01AB1234",
        make: "Bajaj Pulsar",
        color: "Black",
        metadata: ["Recovered near ATM lane", "Partial fingerprint pending", "Number plate replaced"],
        boardType: "vehicle photo",
      },
    },
    {
      id: "evidence:phone",
      type: "evidenceNode",
      position: { x: 1450, y: 470 },
      data: {
        entityType: "evidence",
        recordId: "phone",
        title: "Recovered stolen phone",
        category: "Digital evidence",
        metadata: ["IMEI 356789112233441", "Found on deceased person", "Last tower near ATM at 21:42"],
        boardType: "digital evidence",
      },
    },
    {
      id: "mo:helmet",
      type: "moNode",
      position: { x: 790, y: 640 },
      data: {
        entityType: "modusOperandi",
        recordId: "helmet",
        title: "Helmet-masked two-wheeler operation",
        metadata: ["Evening timing", "Two-person movement", "Vehicle swapped after offence"],
        boardType: "MO note",
      },
    },
    {
      id: "evidence:fingerprint",
      type: "evidenceNode",
      position: { x: 360, y: 650 },
      data: {
        entityType: "evidence",
        recordId: "fingerprint",
        title: "Partial fingerprint",
        category: "Forensic",
        boardType: "fingerprint card",
        metadata: ["Lifted from bike handle", "12-point partial", "Lab confidence 0.71", "Pending AFIS confirmation"],
      },
    },
    {
      id: "evidence:cctv",
      type: "evidenceNode",
      position: { x: 1220, y: 720 },
      data: {
        entityType: "evidence",
        recordId: "cctv",
        title: "ATM CCTV frame",
        category: "Image evidence",
        boardType: "CCTV still",
        imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=260&q=80",
        metadata: ["Helmet glare", "Blue bike visible", "Timestamp 21:39", "Face not visible"],
      },
    },
    {
      id: "evidence:knife",
      type: "evidenceNode",
      position: { x: 850, y: 70 },
      data: {
        entityType: "evidence",
        recordId: "knife",
        title: "Recovered knife",
        category: "Weapon",
        boardType: "weapon photo",
        metadata: ["Not used in ATM case", "Found with associate", "Possible intimidation tool"],
      },
    },
    {
      id: "doc:statement",
      type: "evidenceNode",
      position: { x: 300, y: 40 },
      data: {
        entityType: "document",
        recordId: "statement",
        title: "Informer statement",
        category: "Human intelligence",
        boardType: "note",
        metadata: ["Same bike seen after theft", "Suspect called 'Red Helmet'", "Statement reliability B2"],
      },
    },
  ],
  edges: [
    { id: "e1", source: "person:arjun", target: "incident:atm", label: "suspect in", type: "smoothstep" },
    { id: "e2", source: "person:arjun", target: "incident:bike", label: "linked by bike", type: "smoothstep" },
    { id: "e3", source: "vehicle:bike", target: "incident:bike", label: "stolen in", type: "smoothstep" },
    { id: "e4", source: "vehicle:bike", target: "incident:atm", label: "seen during", type: "smoothstep" },
    { id: "e5", source: "person:mahesh", target: "person:arjun", label: "associate / cousin", type: "smoothstep" },
    { id: "e6", source: "location:kr", target: "incident:bike", label: "origin", type: "smoothstep" },
    { id: "e7", source: "location:atm", target: "incident:atm", label: "crime scene", type: "smoothstep" },
    { id: "e8", source: "evidence:phone", target: "person:unknown-deceased", label: "found in pocket", type: "smoothstep" },
    { id: "e9", source: "evidence:phone", target: "incident:atm", label: "tower match", type: "smoothstep" },
    { id: "e10", source: "mo:helmet", target: "person:arjun", label: "recurring MO", type: "smoothstep" },
    { id: "e11", source: "mo:helmet", target: "incident:atm", label: "behavioral overlap", type: "smoothstep" },
    { id: "e12", source: "evidence:fingerprint", target: "vehicle:bike", label: "lifted from", type: "smoothstep" },
    { id: "e13", source: "evidence:cctv", target: "incident:atm", label: "visual proof", type: "smoothstep" },
    { id: "e14", source: "evidence:knife", target: "person:mahesh", label: "recovered with", type: "smoothstep" },
    { id: "e15", source: "doc:statement", target: "person:arjun", label: "names alias", type: "smoothstep" },
    { id: "e16", source: "doc:statement", target: "vehicle:bike", label: "mentions bike", type: "smoothstep" },
  ],
};
